.\" Manpage for jobexec.
.\" Contact adaulab at gmail dot com to correct errors or typos.
.TH jobexec 1 "13 Jun 2014" "0.1"
.SH NAME
jobexec \- command line batch job executor
.SH SYNOPSYS
jobexec <command> <cmd param 1> <cmd param 2> ...
.br
jobexec "<command with parameters to be executed through a shell>"

.SH DESCRIPTION
The aim of this utility is to be invoqued from a cron or from other unattended process as a way to keep track of the execution of a batch job. It will execute its parameters and redirect stdout and 
stderr to files in a directory created into /var/tmp/jobexec/

The idea is for this directory to contain the running outputs of batch jobs, so their execution can be audited and or monitored.

.SH FILES
.TP
.B /var/tmp/jobexec/<processname>.<hash>/<timestamp>/ 
"basedir" directory where the following status files related to the job will be left
.TP
.B <basedir>/command
the command line that was run
.TP
.B <basedir>/stdout
stdout job output
.TP
.B <basedir>/stderr
stderr job output
.TP
.B <basedir>/running
if present, the job is running, and the file contains the pid
.TP
.B <basedir>/finished
if present, the job finished, and the file contains the error level
.TP
.B <basedir>/exec_time
time taken by the job to finish execution
.TP
.B <basedir>/failed
if present, the job failed to run (it couldnt be executed)
.TP
.B <basedir>/bad_exit_status
if present, the job finished with an exit status other than 0

.SH AUTHOR
Alejandro Dau \- adaulab at gmail dot com

.SH BUGS
It will leave output in disk, so it will accumulate over time. You can leave the expiration of the files up
to the OS (some Unixes have a regular process that deletes unaccesed files in the /tmp and /var/tmp dirs). 
Or you can add the following to your crontab to delete all reports older than 5 days:

.B 7 5 * * *  jobexec find /var/tmp/jobexec/ -mtime +5 -delete -print

jobexec does not currently support Unicode parameters. As a workaround you can put them in a shell script and inboke that script from jobexec. 
 

